language: generic

notifications:
  email: false

branches:
  only:
    - sprint/june1
matrix:
  include:
    - env: TARGET=./client
    - env: TARGET=./server

script: if .travis/build-condition.sh $TRAVIS_COMMIT_RANGE $TARGET; then echo "$TARGET is being built" && cd $TARGET && npm install && ng build --prod --aot; else echo "$TARGET is NOT being built"; fi
