# This is a sample build configuration for JavaScript.
# Check our guides at https://confluence.atlassian.com/x/14UWN for more examples.
# Only use spaces to indent your .yml configuration.
# -----
# You can specify a custom docker image from Docker Hub as your build environment.
image: node:10.15.3

pipelines:
    default:
        - step:
            script:
                - npm install -g --silent @ionic/angular-toolkit
                - npm install -g --silent @angular/cli
                - npm install
                - npm run build

        - step:
            name: Deploy to S3
            deployment: production
            script:
            - pipe: atlassian/aws-s3-deploy:0.3.8
              variables:
                    AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID
                    AWS_SECRET_ACCESS_KEY: $AWS_SECRET_ACCESS_KEY
                    AWS_DEFAULT_REGION: 'us-east-1'
                    S3_BUCKET: 'opengrants.com'
                    LOCAL_PATH: 'www'
                    ACL: 'public-read'